[aws]
format = ' [\[$symbol($profile)(\($region\))(\[$duration\])\]]($style)'

[bun]
format = ' [\[$symbol($version)\]]($style)'

[c]
format = ' [\[$symbol($version(-$name))\]]($style)'
detect_extensions = ['c', 'h', 'cpp', 'hpp']

[cmake]
format = ' [\[$symbol($version)\]]($style)'
detect_files = ['CMakeLists.txt']

[cmd_duration]
format = ' [\[⏱ $duration\]]($style)'
min_time = 0
show_milliseconds = true

[cobol]
format = ' [\[$symbol($version)\]]($style)'

[conda]
format = ' [\[$symbol$environment\]]($style)'

[crystal]
format = ' [\[$symbol($version)\]]($style)'

[daml]
format = ' [\[$symbol($version)\]]($style)'

[dart]
format = ' [\[$symbol($version)\]]($style)'

[deno]
format = ' [\[$symbol($version)\]]($style)'

[docker_context]
format = ' [\[$symbol$context\]]($style)'

[dotnet]
format = ' [\[$symbol($version)(🎯 $tfm)\]]($style)'

[elixir]
format = ' [\[$symbol($version \(OTP $otp_version\))\]]($style)'

[elm]
format = ' [\[$symbol($version)\]]($style)'

[rlang]
format = ' [\[$symbol($version)\]]($style)'

[fennel]
format = ' [\[$symbol($version)\]]($style)'

[fossil_branch]
format = ' [\[$symbol$branch\]]($style)'

[gcloud]
format = ' [\[$symbol$account(@$domain)(\($region\))\]]($style)'

[git_branch]
symbol = ''
format = ' [\[git:$symbol$branch\]](bold purple)'

[git_status]
conflicted = '🏳'
ahead = '🏎💨'
behind = '😰'
diverged = '😵'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'
format = '[\[$all_status$ahead_behind\]]($style)'

[golang]
symbol = " "
format = ' [\[$symbol($version)\]](blue blod)'

[gradle]
format = ' [\[$symbol($version)\]]($style)'

[guix_shell]
format = ' [\[$symbol\]]($style)'

[haskell]
format = ' [\[$symbol($version)\]]($style)'

[haxe]
format = ' [\[$symbol($version)\]]($style)'

[helm]
format = ' [\[$symbol($version)\]]($style)'

[hg_branch]
format = ' [\[$symbol$branch\]]($style)'

[java]
format = ' [\[$symbol($version)\]]($style)'

[julia]
format = ' [\[$symbol($version)\]]($style)'

[kotlin]
format = ' [\[$symbol($version)\]]($style)'

[kubernetes]
format = ' [\[$symbol$context( \($namespace\))\]]($style)'

[lua]
format = ' [\[$symbol($version)\]]($style)'

[memory_usage]
disabled = false
format = ' [\[$symbol$ram( | $swap)\]](bold dimmed green)'

[meson]
format = ' [\[$symbol$project\]]($style)'

[nim]
format = ' [\[$symbol($version)\]]($style)'

[nix_shell]
format = ' [\[$symbol$state( \($name\))\]]($style)'

[nodejs]
symbol = " "
format = ' [\[$symbol$version\]](green bold)'

[ocaml]
format = ' [\[$symbol($version)(\($switch_indicator$switch_name\))\]]($style)'

[opa]
format = ' [\[$symbol($version)\]]($style)'

[openstack]
format = ' [\[$symbol$cloud(\($project\))\]]($style)'

[os]
format = ' [\[$symbol\]]($style)'

[package]
format = ' [\[$symbol$version\]]($style)'

[perl]
format = ' [\[$symbol($version)\]]($style)'

[php]
symbol = " "
format = ' [\[php:$symbol$version\]](147 bold)'

[pijul_channel]
format = ' [\[$symbol$channel\]]($style)'

[pulumi]
format = ' [\[$symbol$stack\]]($style)'

[purescript]
format = ' [\[$symbol($version)\]]($style)'

[python]
format = ' [\[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))\]]($style)'

[raku]
format = ' [\[$symbol($version-$vm_version)\]]($style)'

[red]
format = ' [\[$symbol($version)\]]($style)'

[ruby]
format = ' [\[$symbol($version)\]]($style)'

[rust]
format = ' [\[$symbol($version)\]]($style)'

[scala]
format = ' [\[$symbol($version)\]]($style)'

[spack]
format = ' [\[$symbol$environment\]]($style)'

[sudo]
format = ' [\[as $symbol\]]($style)'

[swift]
format = ' [\[$symbol($version)\]]($style)'

[terraform]
format = ' [\[$symbol$workspace\]]($style)'

[vagrant]
format = ' [\[$symbol($version)\]]($style)'

[vlang]
format = ' [\[$symbol($version)\]]($style)'

[zig]
format = '[\[$symbol($version)\]]($style)'

[solidity]
format = ' [\[$symbol($version)\]]($style)'


[time]
disabled = false
time_format = "%T" # Hour:Minute:Second Format
format = '[\[$time\]](yellow bold) '

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[directory]
read_only = '[🔒]'
format = ' in [$path](bold yellow)[$read_only](red)'

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[username]
style_user = 'blue bold'
style_root = 'yellow bold'
format = '[#](blue bold) [$user]($style)'
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchai" }

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold red) @ [$hostname](bold green)'
trim_at = '.companyname.com'
disabled = false